version: '3'

services: 
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - sonarqube:/opt/sonarqube/data
# Add extra Java options by uncommenting the following lines
#    environment:
#      - EXTRA_JAVA_OPTIONS=-Xmx4g
#    restart: always
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 32000
#        hard: 48000

volumes:
  sonarqube:
      
