version: '3'
services: 
  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    ports:
      - 8181:8081
    volumes:
      - nexus3:/nexus-data
# Add extra Java options by uncommenting the following lines
#    environment:
#      - EXTRA_JAVA_OPTIONS=-Xmx4g
#    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 48000

volumes:
  nexus3:
