version: "3"

services: 
  jenkins:
    image: jenkins/jenkins:lts
    #image: jdufner/jenkins:latest
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /home/jdufner/jenkins:/var/jenkins_home
# Add extra Java options by uncommenting the following lines
#    environment:
#      - EXTRA_JAVA_OPTIONS=-Xmx4g
#    restart: always
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 32000
#        hard: 48000
