version: '3'

services: 
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo:/data/db
    restart: always
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 32000
#        hard: 48000
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    restart: always

volumes:
  mongo:
#NOT TESTED!
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: '/my/path'

